### ISSUE TITLE
Anglo-Saxon or latin display

### ISSUE THREAD

**Issue by trebmuh** [brummer10/gxtuner#13]
I'd be great to be able to display either one or the other.
```
A -> La
B -> Si
C -> Do
D -> Ré
E -> Mi
F -> Fa
G -> Sol
```

**Comment by Allfifthstuning** [comment]
That's a good idea. I can make an extra box and switch to choose between the two.

**Comment by Allfifthstuning** [comment]
Done. Please let me know if this is what you mean.
Will also update the help files, when the option is ok.
Hans

**Comment by trebmuh** [comment]
It is fine @Allfifthstuning .
Could I ask for an CLI option to be added then a use doesn't have to switch every time gxtuner is launched?

**Comment by Allfifthstuning** [comment]
`-N doremi` should do the trick!

**Comment by trebmuh** [comment]
Nice, it works @Allfifthstuning !

Side note, I've just seen that if I'm selecting "chromatic", then the display is back to Anglo-saxon notation. All the others choices are fine displaying Latin notation.

**Comment by Allfifthstuning** [comment]
A your right! The chromatic tuner uses his own notenames. But adding a DoReMi option is no problem. Will do so. But may take some time due to the holidays.

**Comment by trebmuh** [comment]
No worries, keep me in the look here.
And enjoy your holidays!

**Comment by Allfifthstuning** [comment]
Done.

**Comment by trebmuh** [comment]
@Allfifthstuning one more suggestion here.

Would that be possible to have a per-user config file then when launched:
- with -N doremi, it's using the Latin notation
- with -N abc, it's using the Anglo-Saxon notation
- without -N, it's using the previous one (stored in the config file)

**Comment by trebmuh** [comment]
@Allfifthstuning another thing, I've just put a comment [in your previous commit](https://github.com/brummer10/gxtuner/commit/281b21af1e9003c1780eacd58cdeba0f5dc59577)
