### ISSUE TITLE
Color choices for the boxes

### ISSUE THREAD

**Issue by trebmuh** [brummer10/gxtuner#15]
![lzk2](https://user-images.githubusercontent.com/8705846/34276258-d9b59ac4-e6a0-11e7-875a-73270ea2b316.png)

The colors of the boxes (specifically the font color) aren't clear enough then, it's hard to see what are the options currently chosen. See in the green rectangle above.

**Comment by Allfifthstuning** [comment]
Yes I thought of that also. will look into that.

**Comment by Allfifthstuning** [comment]
Better?

**Comment by trebmuh** [comment]
It is definitely way better!
Thanks @Allfifthstuning
